---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: collegemicroservicev1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: collegemicroservicev1
    spec:
      containers:
      - name: collegemicroservicev1
        image: vishipayyallore/collegeapiv1
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: collegemicroservicev1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: collegemicroservicev1